
SECRET_KEY = 'thisisasecret'
SQLALCHEMY_DATABASE_URI = 'sqlite:///wsys_db.db'
CSRF_ENABLED = True
USER_ENABLE_EMAIL = False
USER_ENABLE_REGISTER = True
USER_APP_NAME = "Watering App"
SQLALCHEMY_TRACK_MODIFICATIONS = False
API_KEY = 'aec85d0e0f52e5c5e509ff4142a3a822'
